name: 🚀 Feature request
description: Suggest a new feature
title: "[🚀 Feature]: "
labels: feature

body:
  - type: textarea
    attributes:
      label: 🚀 The feature and your motivation
      description: >
        A clear and concise description of your motivation for suggesting this feature.
    validations:
      required: true
