export enum FunctionEnum {
  EPOCH,
  BLOCK,
  TRANSACTION,
  ADDRESS,
  POOL,
  TOKENS,
  SMART_CONTRACT,
  REWARDS,
  STAKE_ADDRESS_REGISTRATION,
  POOL_REGISTRATION,
  PROTOCOL_PARAMETER,
  NETWORK_MONITORING,
  TRACEABILITY_PROGRAM,
  SUSTAINABILITY_INDICATORS,
  GOVERNANCE,
  STAKING_LIFECYCLE
}
